# Generated by Django 4.2.16 on 2024-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("lotto_id", models.IntegerField()),
                ("number_one", models.IntegerField()),
                ("number_two", models.IntegerField()),
                ("number_three", models.IntegerField()),
                ("number_four", models.IntegerField()),
                ("number_five", models.IntegerField()),
                ("number_six", models.IntegerField()),
            ],
            options={"db_table": "lotto",},
        ),
    ]
