# Generated by Django 4.2.16 on 2024-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottoTest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("lotto_id", models.IntegerField()),
                ("number_one", models.IntegerField()),
                ("number_two", models.IntegerField()),
                ("number_three", models.IntegerField()),
                ("number_four", models.IntegerField()),
                ("number_five", models.IntegerField()),
                ("number_six", models.IntegerField()),
            ],
            options={"db_table": "lotto",},
        ),
        migrations.RemoveField(model_name="excelfile", name="lotto_id",),
        migrations.RemoveField(model_name="excelfile", name="number_five",),
        migrations.RemoveField(model_name="excelfile", name="number_four",),
        migrations.RemoveField(model_name="excelfile", name="number_one",),
        migrations.RemoveField(model_name="excelfile", name="number_six",),
        migrations.RemoveField(model_name="excelfile", name="number_three",),
        migrations.RemoveField(model_name="excelfile", name="number_two",),
        migrations.RemoveField(model_name="excelfile", name="uploaded_at",),
        migrations.AlterModelTable(name="excelfile", table=None,),
    ]
