# Generated by Django 4.2.16 on 2024-12-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottoTest', '0002_lotto_remove_excelfile_lotto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('remain_membership_time', models.DateTimeField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_ad_type', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('cam_campaign_name', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoTest.member')),
            ],
            options={
                'db_table': 'campaign',
            },
        ),
        migrations.DeleteModel(
            name='Lotto',
        ),
        migrations.AlterModelTable(
            name='excelfile',
            table='lotto',
        ),
    ]
