# Generated by Django 4.2.16 on 2024-12-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lottoTest", "0003_member_campaign_delete_lotto_alter_excelfile_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Margin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mar_campaign_id", models.CharField(max_length=255)),
                ("mar_date", models.DateField()),
                ("mar_target_efficiency", models.FloatField()),
                ("mar_ad_revenue", models.FloatField()),
                ("mar_ad_budget", models.FloatField()),
                ("mar_ad_cost_ratio", models.FloatField()),
                ("mar_cpc_unit_cost", models.FloatField()),
                ("mar_impressions", models.BigIntegerField()),
                ("mar_clicks", models.BigIntegerField()),
                ("mar_ad_conversion_sales", models.BigIntegerField()),
                ("mar_actual_sales", models.BigIntegerField()),
                ("mar_ad_margin", models.BigIntegerField()),
                ("mar_net_profit", models.FloatField()),
            ],
            options={"db_table": "margin",},
        ),
        migrations.RemoveField(model_name="campaign", name="id",),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="email",
            field=models.ForeignKey(
                db_column="email",
                on_delete=django.db.models.deletion.CASCADE,
                to="lottoTest.member",
            ),
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mem_date", models.DateField()),
                ("mem_content", models.TextField()),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottoTest.campaign",
                    ),
                ),
            ],
            options={"db_table": "memo",},
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("key_keyword", models.CharField(max_length=255)),
                ("key_impressions", models.BigIntegerField()),
                ("key_clicks", models.BigIntegerField()),
                ("key_click_rate", models.FloatField()),
                ("key_total_sales", models.BigIntegerField()),
                ("key_cvr", models.FloatField()),
                ("key_cpc", models.FloatField()),
                ("key_adcost", models.FloatField()),
                ("key_adsales", models.FloatField()),
                ("key_roas", models.FloatField()),
                ("key_date", models.DateField()),
                ("key_search_type", models.CharField(max_length=255)),
                ("key_exclude_flag", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottoTest.campaign",
                    ),
                ),
            ],
            options={"db_table": "keyword",},
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "execution_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("exe_product_name", models.CharField(max_length=255)),
                ("exe_detail_category", models.CharField(max_length=255)),
                (
                    "campaign_id",
                    models.ForeignKey(
                        db_column="campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottoTest.campaign",
                    ),
                ),
            ],
            options={"db_table": "execution",},
        ),
        migrations.CreateModel(
            name="CampaignOptionDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cop_date", models.DateField()),
                ("cop_impressions", models.BigIntegerField()),
                ("cop_sales", models.BigIntegerField()),
                ("cop_adcost", models.FloatField()),
                ("cop_adsales", models.FloatField()),
                ("cop_roas", models.FloatField()),
                ("cop_clicks", models.BigIntegerField()),
                ("cop_click_rate", models.FloatField()),
                ("cop_cvr", models.FloatField()),
                ("cop_search_type", models.CharField(max_length=255)),
                (
                    "execution",
                    models.ForeignKey(
                        db_column="execution_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottoTest.execution",
                    ),
                ),
            ],
            options={"db_table": "campaign_option_details",},
        ),
    ]
